'use client';
import { ChevronDown, Globe2, Menu, UserRound, X } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { useAuth } from '@/lib/auth';

const links = [{href:'/schemes',label:'Schemes'},{href:'/eligibility',label:'Eligibility'},{href:'/calculator',label:'EMI calculator'},{href:'/partners',label:'Find partners'},{href:'/assistant',label:'AI assistant'}];
const languages = [{code:'en',label:'English'},{code:'hi',label:'हिन्दी'},{code:'gu',label:'ગુજરાતી'}];
export default function Navbar() {
 const {user,logout,isAuthenticated}=useAuth(); const [open,setOpen]=useState(false); const [language,setLanguage]=useState('en'); const [langOpen,setLangOpen]=useState(false);
 return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2.5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0d5c4e] text-sm font-bold text-[#f4cf70]">US</div><div><p className="font-semibold leading-4 text-slate-900">UdyamSathi</p><p className="text-[10px] font-medium tracking-wide text-slate-500">FINANCIAL ACCESS</p></div></Link><nav className="hidden items-center gap-6 lg:flex">{links.map(link=><Link className="text-sm font-medium text-slate-600 transition hover:text-emerald-800" href={link.href} key={link.href}>{link.label}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><div className="relative"><button onClick={()=>setLangOpen(!langOpen)} className="flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-sm text-slate-600 hover:bg-slate-100"><Globe2 className="h-4 w-4" />{languages.find(x=>x.code===language)?.label}<ChevronDown className="h-3.5 w-3.5" /></button>{langOpen&&<div className="absolute right-0 mt-2 w-32 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl">{languages.map(x=><button key={x.code} onClick={()=>{setLanguage(x.code);setLangOpen(false)}} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-emerald-50">{x.label}</button>)}</div>}</div>{isAuthenticated?<div className="flex items-center gap-2"><Link href="/dashboard" className="flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100"><UserRound className="h-4 w-4" />{user?.name}</Link><button onClick={logout} className="text-sm font-medium text-rose-600">Logout</button></div>:<><Link href="/auth/login" className="px-3 py-2 text-sm font-semibold text-slate-700">Sign in</Link><Link href="/eligibility" className="rounded-lg bg-[#0d5c4e] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#08483e]">Get started</Link></>}</div><button onClick={()=>setOpen(!open)} className="rounded-lg p-2 text-slate-700 lg:hidden" aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-slate-200 bg-white px-5 py-4 lg:hidden"><nav className="grid gap-1">{links.map(link=><Link onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3 text-sm font-medium text-slate-700 hover:bg-emerald-50" href={link.href} key={link.href}>{link.label}</Link>)}<Link onClick={()=>setOpen(false)} href="/eligibility" className="mt-2 rounded-lg bg-[#0d5c4e] px-3 py-3 text-center text-sm font-semibold text-white">Check eligibility</Link></nav></div>}</header>;
}
