import type { ChannelPartner, EligibilityInput, Scheme } from '@/types';

export const schemes: Scheme[] = [
  { id: 'nsfdc-term', name: 'NSFDC Term Loan', scheme_type: 'TERM_LOAN', description: 'Concessional term loan for SC entrepreneurs starting or expanding an income-generating business.', max_income: 500000, min_loan: 140001, max_loan: 4500000, interest_rate: 8, max_tenure: 120, moratorium: 6, eligible_purposes: ['business', 'micro_enterprise', 'self_employment'], eligible_categories: ['SC'], min_age: 18, max_age: 55, required_documents: ['SC Certificate', 'Income Certificate', 'Aadhaar', 'Bank account details', 'Project report'], subsidy_info: 'Concessional interest through State Channelizing Agencies.', partner_types: ['SCA'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'nsfdc-micro', name: 'NSFDC Micro Credit Finance', scheme_type: 'MICRO_CREDIT', description: 'Small, concessional credit for SC individuals undertaking micro enterprises and self-employment.', max_income: 500000, min_loan: 5000, max_loan: 140000, interest_rate: 6.5, max_tenure: 60, moratorium: 3, eligible_purposes: ['business', 'micro_enterprise', 'self_employment'], eligible_categories: ['SC'], min_age: 18, max_age: 55, required_documents: ['SC Certificate', 'Income Certificate', 'Aadhaar', 'Bank account details', 'Activity details'], partner_types: ['SCA', 'NBFC_MFI'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'education', name: 'NSFDC Education Loan', scheme_type: 'EDUCATION_LOAN', description: 'Concessional education finance for SC students pursuing professional or technical courses.', max_income: 500000, min_loan: 50000, max_loan: 4000000, interest_rate: 6.5, max_tenure: 84, moratorium: 12, eligible_purposes: ['education'], eligible_categories: ['SC'], min_age: 17, max_age: 35, required_documents: ['SC Certificate', 'Income Certificate', 'Aadhaar', 'Admission letter', 'Fee structure', 'Mark sheets'], partner_types: ['SCA', 'PSB'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'standup', name: 'Stand-Up India', scheme_type: 'TERM_LOAN', description: 'Bank finance for SC/ST and women entrepreneurs setting up a greenfield enterprise.', min_loan: 1000000, max_loan: 10000000, interest_rate: 10, interest_rate_max: 12, max_tenure: 84, moratorium: 18, eligible_purposes: ['business', 'micro_enterprise'], eligible_categories: ['SC', 'ST'], min_age: 18, required_documents: ['Caste certificate', 'Aadhaar', 'Business plan', 'Bank account details', 'Business address proof'], subsidy_info: 'Margin money support may be available through other schemes.', partner_types: ['PSB', 'RRB'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'mudra-shishu', name: 'MUDRA Shishu', scheme_type: 'MUDRA', description: 'Micro-finance for very small income-generating businesses.', min_loan: 1000, max_loan: 50000, interest_rate: 10, interest_rate_max: 12, max_tenure: 60, moratorium: 0, eligible_purposes: ['business', 'micro_enterprise', 'self_employment'], eligible_categories: ['SC', 'ST', 'OBC', 'GENERAL'], min_age: 18, required_documents: ['Aadhaar', 'Address proof', 'Activity details', 'Bank account details'], partner_types: ['PSB', 'RRB', 'NBFC_MFI'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'mudra-kishore', name: 'MUDRA Kishore', scheme_type: 'MUDRA', description: 'Finance for established small businesses that need growth capital.', min_loan: 50001, max_loan: 500000, interest_rate: 10, interest_rate_max: 14, max_tenure: 60, moratorium: 0, eligible_purposes: ['business', 'micro_enterprise', 'self_employment'], eligible_categories: ['SC', 'ST', 'OBC', 'GENERAL'], min_age: 18, required_documents: ['Aadhaar', 'Address proof', 'Bank statements', 'Business plan'], partner_types: ['PSB', 'RRB', 'NBFC_MFI'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'pmegp', name: 'PMEGP', scheme_type: 'PMEGP', description: 'Employment-generation programme for new micro-enterprises with category-based subsidy support.', min_loan: 100000, max_loan: 5000000, interest_rate: 10, interest_rate_max: 14, max_tenure: 84, moratorium: 6, eligible_purposes: ['business', 'micro_enterprise'], eligible_categories: ['SC', 'ST', 'OBC', 'GENERAL'], min_age: 18, min_education: '8th_standard', required_documents: ['Aadhaar', 'Address proof', 'Caste certificate', 'Project report', 'Education certificate'], subsidy_info: 'SC/ST applicants may receive up to 35% margin-money subsidy, subject to official rules.', partner_types: ['PSB', 'RRB'], data_status: 'DEMO', active: true, created_at: '2026-01-01' },
  { id: 'mysy-gujarat', name: 'Mukhyamantri Yuva Swavalamban Yojana (MYSY)', scheme_type: 'SUBSIDY', description: 'Gujarat Government higher education assistance for medical, engineering, diploma, and degree students. Up to 50% tuition subsidy (max ₹2,00,000/yr), ₹1,200/mo hostel allowance, and ₹10,000 book grant.', max_income: 600000, min_loan: 10000, max_loan: 200000, interest_rate: 0, max_tenure: 48, moratorium: 0, eligible_purposes: ['education'], eligible_categories: ['SC', 'ST', 'OBC', 'GENERAL'], min_age: 16, max_age: 30, min_education: '10th_standard', required_documents: ['Aadhaar Card', 'Income Certificate', '10th/12th Marksheet', 'Admission Letter', 'Fee Receipt', 'Bank Passbook'], subsidy_info: 'Direct 50% tuition fee subsidy up to ₹2.00 Lakh per annum + hostel assistance.', partner_types: ['SCA', 'PSB'], data_status: 'VERIFIED', active: true, created_at: '2026-01-01' },
  { id: 'digital-gujarat', name: 'Digital Gujarat Post-Matric Scholarship', scheme_type: 'SUBSIDY', description: 'Universal higher education scholarship for SC, ST, and SEBC students in Gujarat. 100% tuition and exam fee waiver via DBT plus monthly maintenance allowance.', max_income: 250000, min_loan: 5000, max_loan: 150000, interest_rate: 0, max_tenure: 12, moratorium: 0, eligible_purposes: ['education'], eligible_categories: ['SC', 'ST', 'OBC'], min_age: 15, max_age: 35, min_education: '10th_standard', required_documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Previous Marksheet', 'College Fee Receipt', 'Bonafide Certificate', 'Bank Passbook'], subsidy_info: '100% compulsory tuition fee waiver deposited directly into Aadhaar-linked bank account.', partner_types: ['SCA'], data_status: 'VERIFIED', active: true, created_at: '2026-01-01' },
];

export const partners: ChannelPartner[] = [
  { id: 'p1', name: 'Gujarat Scheduled Castes Development Corporation', type: 'SCA', address: 'Block 16, Dr. Jivraj Mehta Bhavan, Gandhinagar', state: 'Gujarat', district: 'Gandhinagar', pincode: '382010', latitude: 23.2156, longitude: 72.6369, supported_schemes: ['NSFDC Term Loan', 'NSFDC Micro Credit Finance', 'NSFDC Education Loan'], active: true, capacity_status: 'AVAILABLE', phone: '079-2325-0000' },
  { id: 'p2', name: 'Bank of Baroda – Ashram Road', type: 'PSB', address: 'Ashram Road, Ahmedabad', state: 'Gujarat', district: 'Ahmedabad', pincode: '380009', latitude: 23.0385, longitude: 72.5665, supported_schemes: ['Stand-Up India', 'MUDRA Shishu', 'MUDRA Kishore', 'PMEGP'], active: true, capacity_status: 'AVAILABLE', phone: '1800-258-4455' },
  { id: 'p3', name: 'Gujarat Gramin Bank – Ahmedabad', type: 'RRB', address: 'Naroda Road, Ahmedabad', state: 'Gujarat', district: 'Ahmedabad', pincode: '382345', latitude: 23.0722, longitude: 72.6524, supported_schemes: ['MUDRA Shishu', 'MUDRA Kishore', 'PMEGP'], active: true, capacity_status: 'LIMITED', phone: '079-2281-0044' },
  { id: 'p4', name: 'Mann Deshi Microfinance', type: 'NBFC_MFI', address: 'Satellite Road, Ahmedabad', state: 'Gujarat', district: 'Ahmedabad', pincode: '380015', latitude: 23.026, longitude: 72.526, supported_schemes: ['NSFDC Micro Credit Finance', 'MUDRA Shishu'], active: true, capacity_status: 'AVAILABLE', phone: '1800-000-0000' },
];

export function formatINR(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value); }

export function matchSchemes(input: EligibilityInput) {
  return schemes.map((scheme) => {
    const checks = [
      { criterion: 'Category', passed: scheme.eligible_categories.includes(input.category), detail: `${input.category} ${scheme.eligible_categories.includes(input.category) ? 'is accepted' : 'is not accepted'} for this scheme` },
      { criterion: 'Loan amount', passed: input.loan_amount >= scheme.min_loan && input.loan_amount <= scheme.max_loan, detail: `Allowed range: ${formatINR(scheme.min_loan)} – ${formatINR(scheme.max_loan)}` },
      { criterion: 'Purpose', passed: scheme.eligible_purposes.includes(input.purpose), detail: `Eligible purposes: ${scheme.eligible_purposes.join(', ')}` },
      { criterion: 'Income', passed: !scheme.max_income || input.annual_income <= scheme.max_income, detail: scheme.max_income ? `Maximum family income: ${formatINR(scheme.max_income)}` : 'No income ceiling in demo data' },
      { criterion: 'Age', passed: (!scheme.min_age || input.age >= scheme.min_age) && (!scheme.max_age || input.age <= scheme.max_age), detail: `Allowed age: ${scheme.min_age ?? 18}–${scheme.max_age ?? 'no upper limit'}` },
    ];
    return { scheme, checks, eligible: checks.every((check) => check.passed) };
  });
}
